const fs = require('fs');
const path = require('path');

const VALID_PROFILES = new Set(['standard', 'dashboard']);
const raw = process.env.OMR_PROFILE || 'standard';
const profile = VALID_PROFILES.has(raw) ? raw : 'standard';
if (raw !== profile) {
  console.warn(`Ignoring unknown OMR_PROFILE="${raw}" (expected: ${[...VALID_PROFILES].join(', ')})`);
}

const PROFILES = {
  standard: {
    profile: 'standard',
    productName: 'OpenMarkdownReader',
    bundleId: 'com.jacobcole.openmarkdownreader',
    icon: 'icon.icns',
    devIcon: 'icon-dev.png',
    defaultFile: null,
    defaultWatch: false,
  },
  dashboard: {
    profile: 'dashboard',
    productName: 'Active Projects Dashboard',
    bundleId: 'com.jacobcole.activeprojectsdashboard',
    icon: 'icon-dashboard.icns',
    devIcon: 'icon-dashboard-dev.png',
    defaultFile: path.join(process.env.HOME, 'code', 'active-projects.md'),
    defaultWatch: true,
  },
};

const edition = PROFILES[profile];
const out = path.join(__dirname, '..', 'build-edition.js');
const body = `// Generated by scripts/generate-edition.js — do not edit by hand.
module.exports = ${JSON.stringify(edition, null, 2)};
`;
fs.writeFileSync(out, body);
console.log(`Edition: ${edition.profile} (${edition.productName})`);
